// Source : https://leetcode.com/problems/find-the-difference/
// Author : RQY
// Date   : 2016-08-30
/**********************************************************************************
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 **********************************************************************************/
 class Solution {
 public:
     char findTheDifference(string s, string t) {
         char res;
         int myhash[26];
         memset(myhash, 0, sizeof(myhash));
         for(int i = 0; i < s.length(); ++i){
             myhash[s[i] - 'a'] += 1;
         }
         for(int i = 0; i < t.length(); ++i){
             myhash[t[i] - 'a'] -= 1;

            //如果直接这样写，第三个for循环就不需要了，会更快一些。
            //  if(myhash[t[i] - 'a'] < 0){
            //    res = t[i];
            //    break;
            //  }
         }
         for(int i = 0; i < 26; ++i){
             if(myhash[i]){
                 res = static_cast<char>(i + 'a');
             }
         }
         return res;
     }
 };
